In [1]:
import pandas as pd
student_name=['ram','shyam','seeta','geeta']
marks=[60,70,80,90]
myvar=pd.Series(marks,index=student_name,name='Student_result')
print(myvar)

ram      60
shyam    70
seeta    80
geeta    90
Name: Student_result, dtype: int64

In [4]:
import pandas as pd
calories={'day1':400,'day2':380,'day3':430,'day4':370}
myvar=pd.Series(calories,name='calories Burn per Day')
print(myvar)

day1    400
day2    380
day3    430
day4    370
Name: calories Burn per Day, dtype: int64

In [5]:
import pandas as pd
calories={'day1':400,'day2':380,'day3':430,'day4':370}
myvar=pd.Series(calories,name='calories Burn per Day',index=['day1','day2'])
print(myvar)

day1    400
day2    380
Name: calories Burn per Day, dtype: int64

## series attributes

In [19]:
import pandas as pd
calories={'day1':400,'day2':380,'day3':430,'day4':370}
myvar=pd.Series(calories,name='calories Burn per Day')

In [20]:
print(myvar.size)

4

In [21]:
print(myvar.dtype)

int64

In [22]:
print(myvar.name)

calories Burn per Day

In [23]:
print(myvar.index)

Index(['day1', 'day2', 'day3', 'day4'], dtype='object')

In [24]:
print(myvar.values)

[400 380 430 370]

In [25]:
print(myvar.is_unique)

True

In [29]:
import pandas as pd
subs=pd.read_csv('subs.csv')
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [30]:
type(subs)

pandas.core.frame.DataFrame

In [31]:
import pandas as pd
subs=pd.read_csv('subs.csv',squeeze=True)
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [32]:
subs.describe()

count    365.000000
mean     135.643836
std       62.675023
min       33.000000
25%       88.000000
50%      123.000000
75%      177.000000
max      396.000000
Name: Subscribers gained, dtype: float64

In [35]:
x=subs.min()
print(x)

33

In [36]:
x=subs.max()
print(x)

396

In [37]:
x=subs.median()
print(x)

123.0

In [38]:
x=subs.sum()
print(x)

49510

In [40]:
subs[subs>200].size

59

In [48]:
m=subs.max()
print(subs[subs==subs.max()])

330    396
Name: Subscribers gained, dtype: int64

In [56]:
bd=pd.read_csv('bollywood.csv',index_col='movie',squeeze=True)
bd

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [57]:
bd.describe()

count             1500
unique             566
top       Akshay Kumar
freq                48
Name: lead, dtype: object

In [60]:
bd.head(4)

movie
Uri: The Surgical Strike                Vicky Kaushal
Battalion 609                             Vicky Ahuja
The Accidental Prime Minister (film)      Anupam Kher
Why Cheat India                         Emraan Hashmi
Name: lead, dtype: object

In [59]:
bd.tail(10)

movie
Raaz (2002 film)                    Dino Morea
Zameen (2003 film)                  Ajay Devgn
Waisa Bhi Hota Hai Part II        Arshad Warsi
Devdas (2002 Hindi film)        Shah Rukh Khan
Kaante                        Amitabh Bachchan
Hum Tumhare Hain Sanam          Shah Rukh Khan
Aankhen (2002 film)           Amitabh Bachchan
Saathiya (film)                   Vivek Oberoi
Company (film)                      Ajay Devgn
Awara Paagal Deewana              Akshay Kumar
Name: lead, dtype: object

In [61]:
bd[0]

'Vicky Kaushal'

In [62]:
bd[-5:]

movie
Hum Tumhare Hain Sanam      Shah Rukh Khan
Aankhen (2002 film)       Amitabh Bachchan
Saathiya (film)               Vivek Oberoi
Company (film)                  Ajay Devgn
Awara Paagal Deewana          Akshay Kumar
Name: lead, dtype: object

In [63]:
bd[::2]

movie
Uri: The Surgical Strike                   Vicky Kaushal
The Accidental Prime Minister (film)         Anupam Kher
Evening Shadows                         Mona Ambegaonkar
Fraud Saiyaan                               Arshad Warsi
Manikarnika: The Queen of Jhansi          Kangana Ranaut
                                              ...
Raaz (2002 film)                              Dino Morea
Waisa Bhi Hota Hai Part II                  Arshad Warsi
Kaante                                  Amitabh Bachchan
Aankhen (2002 film)                     Amitabh Bachchan
Company (film)                                Ajay Devgn
Name: lead, Length: 750, dtype: object

In [64]:
bd[[0,1,3,5,7]]

movie
Uri: The Surgical Strike           Vicky Kaushal
Battalion 609                        Vicky Ahuja
Why Cheat India                    Emraan Hashmi
Soni (film)                 Geetika Vidya Ohlyan
Bombairiya                          Radhika Apte
Name: lead, dtype: object

In [66]:
'2 states (2014 film)' in bd

False

In [67]:
'Alia Bhatt' in bd.values

True

In [68]:
bd.index

Index(['Uri: The Surgical Strike', 'Battalion 609',
       'The Accidental Prime Minister (film)', 'Why Cheat India',
       'Evening Shadows', 'Soni (film)', 'Fraud Saiyaan', 'Bombairiya',
       'Manikarnika: The Queen of Jhansi', 'Thackeray (film)',
       ...
       'Raaz (2002 film)', 'Zameen (2003 film)', 'Waisa Bhi Hota Hai Part II',
       'Devdas (2002 Hindi film)', 'Kaante', 'Hum Tumhare Hain Sanam',
       'Aankhen (2002 film)', 'Saathiya (film)', 'Company (film)',
       'Awara Paagal Deewana'],
      dtype='object', name='movie', length=1500)

In [70]:
bd.value_counts(ascending=True)

Juanna Sanghvi       1
Parthaa Akerkar      1
Freny Bhagat         1
Anuj Sachdeva        1
Ankit                1
                    ..
Sanjay Dutt         26
Salman Khan         31
Ajay Devgn          38
Amitabh Bachchan    45
Akshay Kumar        48
Name: lead, Length: 566, dtype: int64

In [74]:
num_movies=bd.value_counts()
num_movies[num_movies>20]

Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
Shah Rukh Khan      22
Emraan Hashmi       21
Name: lead, dtype: int64

In [82]:
marks={'ram':55,'shyam':60,'seeta':65,'geeta':70}
marks_series=pd.Series(marks,name='student_result')
print(list(marks_series))
print(dict(marks_series))
marks_series[1]=100
print(marks_series)
print(100+marks_series)

[55, 60, 65, 70]
{'ram': 55, 'shyam': 60, 'seeta': 65, 'geeta': 70}
ram       55
shyam    100
seeta     65
geeta     70
Name: student_result, dtype: int64
ram      155
shyam    200
seeta    165
geeta    170
Name: student_result, dtype: int64

In [83]:
marks_series>=100

ram      False
shyam     True
seeta    False
geeta    False
Name: student_result, dtype: bool

In [2]:
import pandas as pd
a=pd.Series([2,4,6,8,10])
b=pd.Series([1,3,5,7,9])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

0     3
1     7
2    11
3    15
4    19
dtype: int64
0    1
1    1
2    1
3    1
4    1
dtype: int64
0     2
1    12
2    30
3    56
4    90
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [3]:
print(a==b)
print(a<b)
print(a>b)

0    False
1    False
2    False
3    False
4    False
dtype: bool
0    False
1    False
2    False
3    False
4    False
dtype: bool
0    True
1    True
2    True
3    True
4    True
dtype: bool

# DataFrame

- DataFramee is a 2 dimensional data structure like a 2D array or table with rows and columns

In [4]:
data={'calories':[420,300,400,370],'duration':[50,40,45,35]}
df=pd.DataFrame(data)

print(df)

   calories  duration
0       420        50
1       300        40
2       400        45
3       370        35

In [5]:
print(df.loc[0])

calories    420
duration     50
Name: 0, dtype: int64

In [6]:
print(df.iloc[0])

calories    420
duration     50
Name: 0, dtype: int64

In [7]:
print(df['calories'])

0    420
1    300
2    400
3    370
Name: calories, dtype: int64

In [8]:
print(df.loc[[0,1]])

   calories  duration
0       420        50
1       300        40

In [10]:
data={'calories':[420,300,400,370],'duration':[50,40,45,35]}
df=pd.DataFrame(data,index=['day1','day2','day3','day4'])
df

      calories  duration
day1       420        50
day2       300        40
day3       400        45
day4       370        35

In [12]:
print(df.loc['day1'])

calories    420
duration     50
Name: day1, dtype: int64

In [13]:
print(df.iloc['day1'])

TypeError: Cannot index by location index with a non-integer key

In [14]:
print(df[::2])

      calories  duration
day1       420        50
day3       400        45

In [21]:
data={'Name':['Alice','Bob','Charlie'],'Age':[25,30,35],'city':['New York','Los Angeles','Chicago']}
df=pd.DataFrame(data)
print(df)
print('------------------------')
print(df.loc[0:1])
print('------------------------')
print(df.iloc[0:1])
print('------------------------')
print(df.loc[(df.Age>26)])

      Name  Age         city
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
------------------------
    Name  Age         city
0  Alice   25     New York
1    Bob   30  Los Angeles
------------------------
    Name  Age      city
0  Alice   25  New York
------------------------
      Name  Age         city
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [23]:
data={'A':[1,2,3,4],'B':[5,6,7,8]}
df=pd.DataFrame(data,index=['r1','r2','r3','r4'])
df

    A  B
r1  1  5
r2  2  6
r3  3  7
r4  4  8

In [24]:
df.loc['r2':'r4','B']=99
df

    A   B
r1  1   5
r2  2  99
r3  3  99
r4  4  99

In [25]:
df.iloc[1:3,0]=0
df

    A   B
r1  1   5
r2  0  99
r3  0  99
r4  4  99

In [26]:
df['c']=[10,20,30,40]
df

    A   B   c
r1  1   5  10
r2  0  99  20
r3  0  99  30
r4  4  99  40

In [29]:
df.loc[df['A']==0,'New_col']='Zero'
df

    A   B   c New_col
r1  1   5  10     NaN
r2  0  99  20    Zero
r3  0  99  30    Zero
r4  4  99  40     NaN

In [33]:
df.loc[len(df)]=['John',35,50,'Zero']
df

       A   B   c New_col
r1     1   5  10     NaN
r2     0  99  20    Zero
r3     0  99  30    Zero
r4     4  99  40     NaN
4   John  35  50    Zero

In [34]:
df.index

Index(['r1', 'r2', 'r3', 'r4', 4], dtype='object')

In [35]:
df.columns

Index(['A', 'B', 'c', 'New_col'], dtype='object')

In [36]:
df.size

20

In [37]:
df.values

array([[1, 5, 10, nan],
       [0, 99, 20, 'Zero'],
       [0, 99, 30, 'Zero'],
       [4, 99, 40, nan],
       ['John', 35, 50, 'Zero']], dtype=object)

In [39]:
df.dtypes

A          object
B           int64
c           int64
New_col    object
dtype: object