In [3]:
import pandas as pd
df1=pd.DataFrame({
    'student_ID':[1,2,3],
    'Name':['Amit','Riya','John']
})
df2=pd.DataFrame({
    'ID':[1,2,4],
    'marks':[85,90,75]
})
result=pd.merge(df1,df2,left_on='student_ID',right_on='ID')
print(result)

   student_ID  Name  ID  marks
0           1  Amit   1     85
1           2  Riya   2     90

In [4]:
import pandas as pd
df1=pd.DataFrame({
    'student_ID':[1,2,3],
    'Name':['Amit','Riya','John']
})
df2=pd.DataFrame({
    'ID':[1,2,4],
    'marks':[85,90,75]
})
result=pd.merge(df1,df2,left_on='student_ID',right_on='ID',how='outer')
print(result)

   student_ID  Name   ID  marks
0         1.0  Amit  1.0   85.0
1         2.0  Riya  2.0   90.0
2         3.0  John  NaN    NaN
3         NaN   NaN  4.0   75.0

In [7]:
df1=pd.DataFrame({
    'physics':[60,70,80]
},index=[101,102,103])
df2=pd.DataFrame({
    'Name':['Alice','Bob','Charlie']
},index=[101,102,103])
result=pd.merge(df1,df2,left_index=True,right_index=True)
print(result)

     physics     Name
101       60    Alice
102       70      Bob
103       80  Charlie

In [13]:
import pandas as pd
df1=pd.DataFrame({
    'student_ID':[1,2,3],
    'Name':['Amit','Riya','John']
})
df2=pd.DataFrame({
    'marks':[85,90,75]
},index=[1,2,3])
result=pd.merge(df1,df2,left_on='student_ID',right_index=True)
print(result)

   student_ID  Name  marks
0           1  Amit     85
1           2  Riya     90
2           3  John     75

## groupby()
- used to split a DataFrame into groups based on one or more columns, allowing for efficient data analysis and aggregation

In [14]:
import pandas as pd
data={
    'product category':['Electronics','furniture','Electronics','furniture'],
    'sales':[200,150,300,100]
}
df=pd.DataFrame(data)
df

  product category  sales
0      Electronics    200
1        furniture    150
2      Electronics    300
3        furniture    100

In [19]:
result=df.groupby('product category')['sales'].sum()
print(result)

product category
Electronics    500
furniture      250
Name: sales, dtype: int64

In [21]:
result=df.groupby('product category')['sales'].mean()
print(result)

product category
Electronics    250.0
furniture      125.0
Name: sales, dtype: float64

In [22]:
result=df.groupby('product category')['sales'].median()
print(result)

product category
Electronics    250.0
furniture      125.0
Name: sales, dtype: float64

In [25]:
result=df.groupby('product category',as_index=False).count()        #default index True
print(result)

  product category  sales
0      Electronics      2
1        furniture      2

In [26]:
result=df.groupby('product category')['sales'].describe()
print(result)

                  count   mean        std    min    25%    50%    75%    max
product category
Electronics         2.0  250.0  70.710678  200.0  225.0  250.0  275.0  300.0
furniture           2.0  125.0  35.355339  100.0  112.5  125.0  137.5  150.0

In [27]:
result=df.groupby('product category')['sales'].sample()
print(result)

0    200
3    100
Name: sales, dtype: int64

In [28]:
result=df.groupby('product category')['sales'].size()
print(result)

product category
Electronics    2
furniture      2
Name: sales, dtype: int64

In [33]:
result=df.groupby('product category')['sales'].nth(1)
print(result)

2    300
3    100
Name: sales, dtype: int64

In [34]:
result=df.groupby('product category')['sales'].groups
print(result)

{'Electronics': [0, 2], 'furniture': [1, 3]}

In [35]:
result=df.groupby('product category')['sales'].nunique()
print(result)

product category
Electronics    2
furniture      2
Name: sales, dtype: int64

In [36]:
result=df.groupby('product category')['sales'].agg
print(result)

<bound method SeriesGroupBy.aggregate of <pandas.core.groupby.generic.SeriesGroupBy object at 0x000002495CA82AC0>>

In [38]:
df=pd.DataFrame({
    'department':['sales','sales','HR','HR','IT','IT'],
    'salary':[50000,60000,40000,45000,70000,75000],
    'bonus':[5000,6000,2000,2500,8000,8500]
})
result=df.groupby('department').agg({'salary':['mean','max'], 'bonus':'sum'})
print(result)

             salary         bonus
               mean    max    sum
department
HR          42500.0  45000   4500
IT          72500.0  75000  16500
sales       55000.0  60000  11000

In [41]:
result=df.groupby('department').agg('mean')
print(result)

             salary   bonus
department
HR          42500.0  2250.0
IT          72500.0  8250.0
sales       55000.0  5500.0

In [42]:
result=df.groupby('department').agg(meanSalary=('salary','mean'),MaxSalary=('salary','max'),TotalBonus=('bonus','sum'))
print(result)

            meanSalary  MaxSalary  TotalBonus
department
HR             42500.0      45000        4500
IT             72500.0      75000       16500
sales          55000.0      60000       11000

In [43]:
df=pd.DataFrame({
    'Region':['East','East','West','West','East','West'],
    'Sales':[100,150,200,120,110,130],
    'Manager':['A','B','C','D','E','F']
})
df

  Region  Sales Manager
0   East    100       A
1   East    150       B
2   West    200       C
3   West    120       D
4   East    110       E
5   West    130       F