# unit -4  Regression - Model Training & Evaluation


- Simple linear regression
- Multiple linear regression
- Polynomial regression

##### Evaluation using -

- R - squared
- MAE - mean absolute error
- MSE - mean squared error

### Linear Regression

- statistical method used to model the relationship between a dependent variables and one or more independent variables
- The goal of LR is to find the best fitting line that describe the relationship between the variables

In [5]:
import pandas as pd
import numpy as np
df=pd.read_csv("data.csv")
df

     x   y
0   15  49
1   23  63
2   18  58
3   23  60
4   24  58
5   22  61
6   22  60
7   19  63
8   19  60
9   16  52
10  24  62
11  11  30
12  24  59
13  16  49
14  23  68

In [6]:
df.isna().sum()

x    0
y    0
dtype: int64

In [8]:
x=df.iloc[:,0:1]
y=df.iloc[:,-1]
print(x)
print(y)
print(type(x))
print(type(y))

     x
0   15
1   23
2   18
3   23
4   24
5   22
6   22
7   19
8   19
9   16
10  24
11  11
12  24
13  16
14  23
0     49
1     63
2     58
3     60
4     58
5     61
6     60
7     63
8     60
9     52
10    62
11    30
12    59
13    49
14    68
Name: y, dtype: int64
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [9]:
print(x.shape)
print(y.shape)

(15, 1)
(15,)

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=1)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(13, 1)
(13,)
(2, 1)
(2,)

In [22]:
# manual way without testing
# from sklearn.linear_model import LinearRegression
# lr=LinearRegression()
# lr.fit(x,y)
# ypred=lr.predict(x)
# print(ypred)
# print(x)
# print(y)

[47.45652174 62.60810811 53.13836663 62.60810811 64.5020564  60.71415981
 60.71415981 55.03231492 55.03231492 49.35047004 64.5020564  39.88072855
 64.5020564  49.35047004 62.60810811]
     x
0   15
1   23
2   18
3   23
4   24
5   22
6   22
7   19
8   19
9   16
10  24
11  11
12  24
13  16
14  23
0     49
1     63
2     58
3     60
4     58
5     61
6     60
7     63
8     60
9     52
10    62
11    30
12    59
13    49
14    68
Name: y, dtype: int64

In [ ]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
ypred=lr.predict(x_test)
print(ypred)

In [21]:
print(x_test)

    x
3  23
7  19

In [17]:
print(y_test)

3    60
7    63
Name: y, dtype: int64

In [18]:
diff=pd.DataFrame({"Actual":y_test,"Predicted":ypred})
diff

   Actual  Predicted
3      60  62.413229
7      63  54.568279

In [19]:
print("Coefficient: ",lr.coef_)
print("intercept: ",lr.intercept_)

Coefficient:  [1.96123755]
intercept:  17.30476529160739

In [26]:
from sklearn import metrics
print("MAE: ",metrics.mean_absolute_error(y,ypred))
print("MSE: ",metrics.mean_squared_error(y,ypred))
print("R2 square: ",metrics.r2_score(y,ypred))

MAE:  3.7412847630238946
MSE:  22.292068155111636
R2 square:  0.7088287858527738